//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seferi_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuzergahDuraklari
    {
        public int GuzergahID { get; set; }
        public int DurakID { get; set; }
        public int Sira { get; set; }
    
        public virtual Duraklar Duraklar { get; set; }
        public virtual Guzergahlar Guzergahlar { get; set; }
    }
}
