//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seferi_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seferler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seferler()
        {
            this.Rezervasyonlars = new HashSet<Rezervasyonlar>();
        }
    
        public int SeferID { get; set; }
        public int GuzergahID { get; set; }
        public System.DateTime TarihSaat { get; set; }
        public byte[] Aciklama { get; set; }
    
        public virtual Guzergahlar Guzergahlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyonlar> Rezervasyonlars { get; set; }
    }
}
